import Head from 'next/head'
import Navbar from '@/components/navbar/navbar'
import Footer from '@/layout/FooterContainer/footerContainer'
import Preloader from '@/components/preloader/preloader'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Desarrollo Infantil Inclusivo: Guía para el Espectro Autista (1-5 años)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Preloader />
      <Navbar />
      <section className={styles['ripple-background']}>
      <div className={`${styles.circle} ${styles.xxlarge} ${styles.shade1}`}></div>
      <div className={`${styles.circle} ${styles.xlarge} ${styles.shade2}`}></div>
      <div className={`${styles.circle} ${styles.large} ${styles.shade3}`}></div>
      <div className={`${styles.circle} ${styles.medium} ${styles.shade4}`}></div>
      <div className={`${styles.circle} ${styles.small} ${styles.shade5}`}></div>
      </section>
      <section></section>
      <section></section>
      <section></section>
      <Footer/>
    </>
  )
}
