import Head from 'next/head'
import Navbar from '@/components/navbar/navbar'
import Footer from '@/layout/FooterContainer/footerContainer'
import Preloader from '@/components/preloader/preloader'
import styles from '@/styles/Home.module.css'
import BackgroundPatron1 from '@/layout/BackgroundPatron1/backgrounPatron'
import BackgroundGradient from '@/layout/BackgroundGradient/backgroundGradient'
import BackgroundCircular from '@/layout/BackgroundCircular/backgroundCircular'
export default function Home() {
  return (
    <>
      <Head>
        <title>Desarrollo Infantil Inclusivo: Guía para el Espectro Autista (1-5 años)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Preloader />
      <Navbar />

      <BackgroundPatron1 patron={1} />
      <BackgroundPatron1 patron={2} />
      <BackgroundGradient patron={1}/>
      <BackgroundCircular patron={1}/>
      <BackgroundCircular patron={2}/>
      {/* <section></section> */}
      <Footer/>
    </>
  )
}
